import { useRef } from "react";
import confetti from "canvas-confetti";

interface Props {
  /** Fires after the user clicks acknowledge and confetti runs. */
  onAck: () => void;
}

/** Shown every time a user lands on the plan screen (no persistence).
 *  Different wording from the first-visit SEBI modal — this one's plan-
 *  specific (AI, not certified, consult an advisor). Fires canvas-confetti
 *  on dismiss. */
export default function PlanRevealModal({ onAck }: Props) {
  const hasRun = useRef(false);

  const dismiss = () => {
    if (hasRun.current) return;
    hasRun.current = true;
    // A few confetti bursts from different origins for a fuller effect.
    const opts = { particleCount: 80, spread: 70, origin: { y: 0.4 } };
    confetti(opts);
    setTimeout(() => confetti({ ...opts, particleCount: 50, angle: 60 }), 150);
    setTimeout(() => confetti({ ...opts, particleCount: 50, angle: 120 }), 300);
    onAck();
  };

  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-900/70 backdrop-blur-sm px-4">
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-2xl max-w-md w-full p-6 space-y-5 border-2 border-primary-200 dark:border-primary-700">
        <div className="w-14 h-14 rounded-full bg-primary-100 dark:bg-primary-900/40 mx-auto flex items-center justify-center">
          <span aria-hidden className="text-2xl">🎉</span>
        </div>
        <div className="text-center">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-slate-100">Your plan is ready</h2>
          <p className="mt-3 text-sm text-gray-600 dark:text-slate-300 leading-relaxed text-left">
            This plan was generated by an AI model for
            {" "}<span className="font-medium text-gray-900 dark:text-slate-100">
              research and educational purposes only
            </span>. It is not certified financial advice. Before acting on any
            of these recommendations:
          </p>
          <ul className="mt-3 text-sm text-gray-600 dark:text-slate-300 space-y-1.5 text-left list-disc list-inside">
            <li>Verify the funds and allocation with your own research</li>
            <li>Consult a <span className="font-medium">SEBI-registered investment advisor</span></li>
            <li>Consider your full financial picture, not just this input</li>
          </ul>
        </div>
        <button onClick={dismiss} className="btn btn-primary w-full py-2.5 text-base">
          I understand — show my plan
        </button>
      </div>
    </div>
  );
}
