#!/usr/bin/env bash
# Blue-green deploy orchestrator.
#
#   1. Figure out which colour is inactive (active = content of
#      /etc/caddy/active-finadvisor.caddy's reverse_proxy line).
#   2. Build the frontend + Docker image.
#   3. Tag the image per-colour and update the Nomad job for the inactive
#      colour only (terraform apply -var).
#   4. Wait for it to be healthy, run smoke.sh against it via
#      X-Benji-Color header.
#   5. Query HyperDX for errors / log-errors in the last 5 min on the
#      inactive colour. If clean → flip Caddy, reload; if dirty → abort.
#   6. Emit a DORA OTEL span at each decision point.
#
# Usage:
#   scripts/blue-green-deploy.sh [--auto-promote]     # default asks to promote
#   scripts/blue-green-deploy.sh --force-color green  # override target colour

set -euo pipefail

AUTO_PROMOTE=0
FORCE_COLOR=""
SMOKE_WAIT_SECS=20
HEALTH_WINDOW_MIN=3
MAX_ERRORS=0
MAX_LOG_ERRORS=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --auto-promote) AUTO_PROMOTE=1; shift ;;
        --force-color)  FORCE_COLOR="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NOMAD_JOBS="$HOME/projects/nomad/jobs"
CADDY_ACTIVE="/etc/caddy/active-finadvisor.caddy"
PORT_BLUE=8091
PORT_GREEN=8093

log() { echo "[$(date -u +%H:%M:%S)] $*"; }
die() { echo "[$(date -u +%H:%M:%S)] ✗ $*" >&2; exit 1; }

emit_dora() {
    local status="$1" reason="${2:-}" color="${3:-$target}"
    if [[ -n "${SKIP_DORA:-}" ]]; then return 0; fi
    uv run --directory "$REPO_ROOT/product" python "$REPO_ROOT/scripts/dora_emit.py" \
        --color "$color" \
        --image "finadvisor:${color}-${image_tag}" \
        --status "$status" \
        ${reason:+--reason "$reason"} \
        >/dev/null 2>&1 || log "(dora emit failed, continuing)"
}

# 1. Which colour is active?
if [[ -r "$CADDY_ACTIVE" ]]; then
    if grep -q ":${PORT_BLUE}" "$CADDY_ACTIVE"; then
        active="blue";  target="green"
    elif grep -q ":${PORT_GREEN}" "$CADDY_ACTIVE"; then
        active="green"; target="blue"
    else
        die "$CADDY_ACTIVE exists but references neither port — please fix"
    fi
else
    log "$CADDY_ACTIVE missing — assuming blue is active (seeding file after deploy)"
    active="blue"; target="green"
fi
[[ -n "$FORCE_COLOR" ]] && target="$FORCE_COLOR"
log "active=$active   target=$target"

# 2. Build — pre-build gate: fast API smoke + SPA build + UI smoke.
#    Fails here block the deploy before we ever touch Nomad.
image_tag="$(git -C "$REPO_ROOT" rev-parse --short HEAD)-$(date -u +%Y%m%d%H%M%S)"
log "running API smoke (in-process, stubbed LLM)"
make -C "$REPO_ROOT" smoke-api >/dev/null || die "smoke-api failed — strategy/plan contract broken"
log "building frontend"
make -C "$REPO_ROOT" frontend >/dev/null
log "running UI smoke (headless Chromium, stubbed LLM)"
make -C "$REPO_ROOT" smoke-ui >/dev/null || die "smoke-ui failed — strategy/plan page broken"
log "building docker image (tag=$image_tag)"
make -C "$REPO_ROOT" docker   >/dev/null
sudo docker tag finadvisor:local "finadvisor:${target}-${image_tag}"

emit_dora started "" "$target"

# 3. Apply terraform for the target colour only
log "applying nomad job finadvisor-${target} with new image"
TF_VAR_NAME="finadvisor_${target}_image"
( cd "$NOMAD_JOBS" && \
  terraform apply -auto-approve \
      -var="${TF_VAR_NAME}=finadvisor:${target}-${image_tag}" \
      -target="nomad_job.finadvisor_${target}" \
      -replace="nomad_job.finadvisor_${target}" \
      >/dev/null )

log "waiting ${SMOKE_WAIT_SECS}s for $target to become healthy"
sleep "$SMOKE_WAIT_SECS"

# 4. Smoke test against the inactive colour via header
log "running smoke suite against $target"
if ! "$REPO_ROOT/scripts/smoke.sh" "$target"; then
    emit_dora smoke_failed "smoke.sh non-zero" "$target"
    die "smoke failed — leaving $active active, $target on failed image"
fi

# 5. Metrics gate — error rate + log errors in the past N minutes
log "checking HyperDX metrics for $target over last ${HEALTH_WINDOW_MIN} min"
err="$("$REPO_ROOT/scripts/hyperdx_query.sh" errors "$target" "$HEALTH_WINDOW_MIN")"
log_err="$("$REPO_ROOT/scripts/hyperdx_query.sh" log_errors "$target" "$HEALTH_WINDOW_MIN")"
log "  error spans = $err   error logs = $log_err"
if (( err > MAX_ERRORS )) || (( log_err > MAX_LOG_ERRORS )); then
    emit_dora metrics_failed "err=$err log_err=$log_err" "$target"
    die "metrics dirty — NOT promoting $target"
fi

# 6. Promote
if [[ "$AUTO_PROMOTE" == "0" ]]; then
    read -rp "promote $target to receive prod traffic? [y/N] " ack
    [[ "$ack" =~ ^[Yy]$ ]] || { log "not promoting — deploy image staged on $target"; exit 0; }
fi

target_port=$([[ "$target" == "blue" ]] && echo "$PORT_BLUE" || echo "$PORT_GREEN")
log "flipping Caddy → $target (port $target_port)"
sudo tee "$CADDY_ACTIVE" >/dev/null <<EOF
# Auto-generated by blue-green-deploy.sh — do not hand-edit.
# Active colour: $target   (image: finadvisor:${target}-${image_tag})
reverse_proxy localhost:${target_port}
EOF
sudo systemctl reload caddy

emit_dora promoted "active=$target" "$target"
log "✓ promoted $target — $active remains on its previous image as a rollback target"
