#!/usr/bin/env bash
# Emergency rollback — flip Caddy back to the inactive colour.
#
# This does NOT redeploy an image; it just repoints public traffic. Both
# colours are always running, so the "previous" stack is one Caddy
# reload away.

set -euo pipefail

CADDY_ACTIVE="/etc/caddy/active-finadvisor.caddy"
PORT_BLUE=8091
PORT_GREEN=8093
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if ! [[ -r "$CADDY_ACTIVE" ]]; then
    echo "$CADDY_ACTIVE missing — cannot determine current colour" >&2; exit 2
fi
if grep -q ":${PORT_BLUE}" "$CADDY_ACTIVE"; then
    active="blue";  other="green"; other_port=$PORT_GREEN
else
    active="green"; other="blue";  other_port=$PORT_BLUE
fi
echo "rolling back: $active → $other  (port $other_port)"

sudo tee "$CADDY_ACTIVE" >/dev/null <<EOF
# Auto-generated by rollback.sh — do not hand-edit.
reverse_proxy localhost:${other_port}
EOF
sudo systemctl reload caddy

uv run --directory "$REPO_ROOT/product" python "$REPO_ROOT/scripts/dora_emit.py" \
    --color "$other" \
    --image "rollback" \
    --status rolled_back \
    --reason "manual rollback from $active" >/dev/null 2>&1 || true

echo "✓ $other now receives public traffic"
