"""Investment plan model — the structured output of the advisor agent."""

from pydantic import BaseModel, Field
from typing import Literal


class Allocation(BaseModel):
    """A single line item in the investment plan."""

    instrument_name: str = Field(description="Name of instrument, e.g. 'Nifty 50 Index Fund' or 'HDFC Bank'")
    instrument_type: Literal[
        "index_fund", "etf", "mutual_fund_active", "individual_stock",
        "bond", "fixed_deposit", "ppf_epf", "gold", "reit", "other"
    ]
    allocation_pct: float = Field(ge=0, le=100, description="Percentage of portfolio")
    rationale: str = Field(description="Why this instrument for this persona")


class InvestmentPlan(BaseModel):
    """A complete investment plan generated by the advisor agent."""

    allocations: list[Allocation] = Field(description="Portfolio allocation breakdown")
    rebalancing_frequency: Literal[
        "monthly", "quarterly", "semi_annually", "annually", "rarely"
    ] = Field(description="How often the portfolio should be rebalanced")
    expected_annual_return_pct: float = Field(
        description="Expected annual return estimate"
    )
    cost_awareness: str = Field(
        description="How the plan addresses costs, expense ratios, and fees"
    )
    research_approach: str = Field(
        description="What research/analysis the investor should do (if any)"
    )
    overall_strategy_summary: str = Field(
        description="2-3 sentence summary of the investment strategy"
    )
    key_risks: list[str] = Field(
        description="Top risks the investor should be aware of"
    )
    disclaimer: str = Field(
        default="This is a research-generated plan for academic purposes only. Not financial advice."
    )
